language: node_js
node_js:
  - "12"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
install:
  - yarn
before_script:
  - ''
script:
  - yarn run lint
  - yarn run test:unit
  - yarn run build
after_script:
  - echo "ci completed."
